# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do |lane, options|
    @build_type = "Release"
    if not options.empty?
      @build_type = options["release"] ? "Release" : "Debug"
    end
  end

  desc "Assemble Build"
  lane :assemble_build do
    properties = {
      "android.injected.signing.store.file" => "keystore.jks",
      "android.injected.signing.store.password" => ENV['KEY_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['STORE_PASSWORD'],
    } if @build_type == "Release"
    gradle(task: "assemble", build_type: @build_type, properties: properties)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_to_play_store_dev do
    upload_to_play_store(
        package_name: 'com.milwaukee.weather.dev',
        track: 'alpha',
        apk: 'app/build/outputs/apk/dev/release/app-dev-release.apk'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_to_play_store_prod do
    upload_to_play_store(
        package_name: 'com.milwaukee.weather',
        track: 'alpha',
        apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk'
    )
  end
end